
title: Aleksandar Popovic / Popac Development Blog
email: aleksandar.popovic.popac@gmail.com
description: Knowledge was created to be shared.
baseurl: ""
url: "https://mozgovac.github.io"
twitter_username: mozgovac
github_username: mozgovac
disqus_username: mozgovac
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
